build:
	chmod +x create_version_file.sh
	./create_version_file.sh

	gnome-extensions pack --force --extra-source=github.svg --extra-source=utils.js --extra-source=data_repository.js --extra-source=version.js